global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
        labels:
          client: 'client-b'
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: 'prometheus_build_info|prometheus_tsdb_head_samples|prometheus_http_requests_total|go_goroutines'
        action: keep

remote_write:
  - url: http://nginx:9090/api/v1/metrics/write
    headers:
      X-Example-Key: token-client-b-67890  # Pretend we are authenticating as "client-b"
    queue_config:
      capacity: 10000
      max_shards: 5
      min_shards: 1
      max_samples_per_send: 500
      batch_send_deadline: 5s
