volumes:
  debugfs:
    driver: local
    driver_opts:
      type: debugfs
      device: debugfs
      o: uid=0,gid=0,mode=755

services:
  broker:
    image: docker.io/apache/kafka:3.9.1@sha256:4ceccc577f03f51f6af8dbfda55194d0d892f4fa7913ffbded567ce3895622ed
    restart: on-failure:3
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092,PLAINTEXT_HOST://broker:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@broker:29093
      KAFKA_LISTENERS: PLAINTEXT://broker:29092,CONTROLLER://broker:29093,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs
    healthcheck:
      test: ["CMD", "/opt/kafka/bin/kafka-topics.sh", "--list", "--bootstrap-server", "broker:9092"]
      interval: 5s
      timeout: 10s
      retries: 5

  kafka-init:
    image: docker.io/apache/kafka:3.9.1@sha256:4ceccc577f03f51f6af8dbfda55194d0d892f4fa7913ffbded567ce3895622ed
    depends_on:
      - broker
    entrypoint: /bin/sh -c
    command: >
      "
      echo '--- Init container started ---';
      echo 'Waiting for Kafka to be ready...';
      while ! /opt/kafka/bin/kafka-topics.sh --list --bootstrap-server broker:9092 > /dev/null 2>&1; do 
      echo 'Kafka not ready yet, sleeping...';
      sleep 2; 
      done;
      echo 'Kafka is ready! Creating topics...';
      /opt/kafka/bin/kafka-topics.sh --create --topic purchases --partitions 1 --replication-factor 1 --if-not-exists --bootstrap-server broker:9092;
      /opt/kafka/bin/kafka-topics.sh --create --topic topic1 --partitions 1 --replication-factor 1 --if-not-exists --bootstrap-server broker:9092;
      /opt/kafka/bin/kafka-topics.sh --create --topic topic2 --partitions 1 --replication-factor 1 --if-not-exists --bootstrap-server broker:9092;
      echo '--- Topics created successfully ---';
      "

  consumer:
    build:
      context: .
    depends_on:
      kafka-init:
        condition: service_completed_successfully
      otel-lgtm:
        condition: service_started
    environment:
      KAFKA_BOOTSTRAP_SERVERS: "broker:9092"
      KAFKA_TOPIC: "purchases"
      KAFKA_GROUP_ID: "kafka-dotnet-getting-started"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-lgtm:4317"
      OTEL_SERVICE_NAME: "dotnet-kafka-consumer"
    restart: unless-stopped

  otel-lgtm:
    image: docker.io/grafana/otel-lgtm:latest
    ports:
      - "3000:3000"
      - "4317:4317"
      - "4318:4318"
    stop_grace_period: 2s
