version: '3'

services:
  alloy:
    image: docker.io/grafana/alloy:latest
    ports:
      - "12346:12345/tcp"
    environment:
      - GRAFANA_CLOUD_OTLP_ENDPOINT=${GRAFANA_CLOUD_OTLP_ENDPOINT}
      - GRAFANA_CLOUD_INSTANCE_ID=${GRAFANA_CLOUD_INSTANCE_ID}
      - GRAFANA_CLOUD_API_KEY=${GRAFANA_CLOUD_API_KEY}
    volumes:
      - $PWD/alloy/config.alloy:/etc/alloy/config.alloy:z
    command:
      - run
      - --server.http.listen-addr=0.0.0.0:12345
      - --storage.path=/var/lib/alloy/data
      - --stability.level=experimental
      - /etc/alloy/config.alloy

  demoapp:
    build:
      context: demoapp
    volumes:
      - ./demoapp:/app:z
