apiVersion: v1
kind: Service
metadata:
  name: app-uninstrumented
  labels:
    app: app-uninstrumented
spec:
  type: NodePort
  selector:
    app: app-uninstrumented
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30081