apiVersion: v1
kind: Service
metadata:
  name: app-with-sdk
  labels:
    app: app-with-sdk
spec:
  type: NodePort
  selector:
    app: app-with-sdk
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30080