apiVersion: v1
kind: Service
metadata:
  name: dotnet-profile-demo
  labels:
    app: dotnet-profile-demo
spec:
  type: NodePort
  selector:
    app: dotnet-profile-demo
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30080